### ISSUE TITLE
Any "no gutter" row functionnality ?

### ISSUE THREAD

**Issue by fredconv** [matthewsimo/scss-flex-grid#13]
It would be great to have the possibility to remove the default gutter by just adding a class on the parent "row" 
but it should affect only the first level of children cols

**Comment by matthewsimo** [comment]
So, you're imagining a class on the `row` parent that sets column padding to zero for direct children of that row parent. I don't see a huge _need_ for this since it complicates things, but if I see the request come up more and more I can add it in. For now, something like the following would suit your needs I think. The new class to add to rows is `full-row`.

```css
.row.full-row > .col {
  padding-left: 0;
  padding-right: 0;
}
```
