### ISSUE TITLE
npmjs.com release

### ISSUE THREAD

**Issue by janv** [matthewsimo/scss-flex-grid#7]
Hey, are you planning on putting this on npm?
I tried finding it there but couldn't

**Comment by matthewsimo** [comment]
Hi - I've considered it, but ultimately think it's not a good fit because of the required build step.. However, I'm always open to hearing opinions for it. 

Will keep this open, and if there is support or valid arguments in favor I think have merit - I'll be happy to refactor a bit in an effort for a NPM release.

**Comment by janv** [comment]
The way I use it there is no build step required.
I'd use `@import "./node_modules/scss-flex-grid";` from within my own sass files and that's it. Considering that people are building pipelines around consuming CommonJS modules and Preprocessors (think webpack), putting this on npm would be awesome.

**Comment by matthewsimo** [comment]
Realized that I was just being lazy and there was no _good_ reason to not have an NPM version if someone wanted it. Published! https://www.npmjs.com/package/scss-flex-grid :+1:
