### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by fredlesser** [matthewsimo/scss-flex-grid#8]
Hi, I get a horizontal scrollbar which I can only get rid of by giving the first instance of '.row' a property of 'margin: 0'. I noticed that in the example your '#wrapper' div has its negative margin overridden but I couldn't find anything about this in the docs.

**Comment by matthewsimo** [comment]
Hi @fredlesser, sorry you're having trouble - 

I set negative margin on rows [here](https://github.com/matthewsimo/scss-flex-grid/blob/master/_flex-grid.scss#L77) to account for gutter margin on columns. It wasn't mentioned in the docs since it's more of an implementation detail than anything relating to actual usage.

That said, if you could put together a reproducible repo or codepen or something I can take a look. If you think adding a note to the docs would be helpful, I'm happy to consider pull requests.

**Comment by fredlesser** [comment]
Hi @matthewsimo and btw thanks for the awesome grid!!
Fixed the issue by wrapping rows in a .container div with 'padding-left: $fg-gutter' and 'padding-right: $fg-gutter', which is essentially the same as what one does in Bootstrap.
