### ISSUE TITLE
off-md-0 defers to smaller media query offset rather than having no offset

### ISSUE THREAD

**Issue by Kielan** [matthewsimo/scss-flex-grid#9]
if for example the offset for different screen sizes is like: off-md-5 off-sm-0 off-xs-3 the small view size will automatically defer to the xs. 

Critical problem with this flex grid

**Comment by matthewsimo** [comment]
Hi @Kielan - thanks for inquiring about this. So a couple of things:

- there is no '0' offset, it just doesn't make sense to offset something by zero, so if you check the generated CSS you won't find a rule for that class being generated..
- I've written this to be a mobile first approach, so if you are viewing within the 'sm' namespace but there isn't a rule declared for it of course it makes sense that the 'xs' ( or whatever the next smallest namespace you've made for your project ) would kick in. You don't meet the qualifications for the 'md' namespace breakpoint, so that rule won't go into effect.

I hope that helps. I'm sorry you think this is a critical problem, but I adamantly disagree. I'm happy to review a pull request that you think properly addresses your issue though. I really think this is more of an issue with docs being unclear vs. any actual need for a code change.
